version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email contact@onadapp.com --agree-tos --no-eff-email -d onadapp.com

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certbot/renew-hook.sh:/renew-hook.sh
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
        while :; do
          certbot renew --quiet --deploy-hook "/renew-hook.sh";
          sleep 12h;
        done'